// Sprite sheet slicer for Basketbrook Trails.
//
// Reads the multi-sprite sheets in assets/Basketbrook_Trails_gameplay_assets/
// and cuts each individual sprite into its own trimmed PNG under
// assets/sprites/<category>/<index>.png.
//
// Segmentation is done with a transparency projection:
//   1. Find horizontal bands (rows that contain any opaque pixel).
//   2. Inside each band, find vertical columns groups (sprites).
//   3. Tight-trim each sprite to its opaque bounding box.
//
// Run with:  dart run tool/slice_sprites.dart
import 'dart:io';
import 'package:image/image.dart' as img;

const int alphaThreshold = 24; // pixel considered "content" above this alpha
const int minRunPixels = 3; // min opaque pixels in a line to count as content
const int minSpriteSize = 10; // discard specks smaller than this (px)

class Sheet {
  final String file;
  final String category;
  // Minimum gap (in px) of empty lines required to split two sprites.
  final int rowGap;
  final int colGap;
  const Sheet(this.file, this.category, {this.rowGap = 6, this.colGap = 6});
}

const sheets = <Sheet>[
  Sheet('chickens_asset.webp', 'chickens', colGap: 12),
  Sheet('eggs_asset.webp', 'eggs', colGap: 10),
  Sheet('baskets_asset.webp', 'baskets', colGap: 10),
  Sheet('coins_asset.webp', 'coins', colGap: 8),
  Sheet('collectible_items_asset.webp', 'collectibles', colGap: 10),
  Sheet('decorative_asset.webp', 'decorative', colGap: 8),
  Sheet('fences_asset.webp', 'fences', colGap: 14),
  Sheet('obtacles_asset.webp', 'obstacles', colGap: 12),
];

void main() async {
  final srcDir = 'assets/Basketbrook_Trails_gameplay_assets';
  final buffer = StringBuffer();
  buffer.writeln('// GENERATED by tool/slice_sprites.dart. Do not edit by hand.');
  buffer.writeln('// Sprite counts per category:');

  for (final sheet in sheets) {
    final path = '$srcDir/${sheet.file}';
    final bytes = File(path).readAsBytesSync();
    final image = img.decodeImage(bytes);
    if (image == null) {
      stderr.writeln('FAILED to decode $path');
      continue;
    }
    final rgba = image.convert(numChannels: 4);
    final rects = _segment(rgba, sheet.rowGap, sheet.colGap);

    final outDir = Directory('assets/sprites/${sheet.category}');
    if (outDir.existsSync()) outDir.deleteSync(recursive: true);
    outDir.createSync(recursive: true);

    var index = 0;
    for (final r in rects) {
      final cropped = img.copyCrop(
        rgba,
        x: r.x,
        y: r.y,
        width: r.w,
        height: r.h,
      );
      final outPath = '${outDir.path}/$index.png';
      File(outPath).writeAsBytesSync(img.encodePng(cropped));
      index++;
    }
    stdout.writeln(
        '${sheet.category.padRight(14)} -> $index sprites (sheet ${rgba.width}x${rgba.height})');
    buffer.writeln('//   ${sheet.category}: $index');
  }
  stdout.writeln('\nDone.');
}

class Rect {
  final int x, y, w, h;
  Rect(this.x, this.y, this.w, this.h);
}

bool _rowHasContent(img.Image im, int y) {
  var count = 0;
  for (var x = 0; x < im.width; x++) {
    if (im.getPixel(x, y).a >= alphaThreshold) {
      count++;
      if (count >= minRunPixels) return true;
    }
  }
  return false;
}

bool _colHasContent(img.Image im, int x, int y0, int y1) {
  var count = 0;
  for (var y = y0; y < y1; y++) {
    if (im.getPixel(x, y).a >= alphaThreshold) {
      count++;
      if (count >= minRunPixels) return true;
    }
  }
  return false;
}

// Group indices [0..n) into runs of "true" separated by gaps >= minGap of false.
List<List<int>> _runs(List<bool> content, int minGap) {
  final runs = <List<int>>[];
  int? start;
  var emptyRun = 0;
  for (var i = 0; i < content.length; i++) {
    if (content[i]) {
      start ??= i;
      emptyRun = 0;
    } else {
      if (start != null) {
        emptyRun++;
        if (emptyRun >= minGap) {
          runs.add([start, i - emptyRun + 1]);
          start = null;
          emptyRun = 0;
        }
      }
    }
  }
  if (start != null) runs.add([start, content.length]);
  return runs;
}

List<Rect> _segment(img.Image im, int rowGap, int colGap) {
  // 1. Horizontal bands.
  final rowContent = List<bool>.generate(im.height, (y) => _rowHasContent(im, y));
  final bands = _runs(rowContent, rowGap);

  final rects = <Rect>[];
  for (final band in bands) {
    final y0 = band[0];
    final y1 = band[1];
    if (y1 - y0 < minSpriteSize) continue;
    // 2. Columns inside the band.
    final colContent =
        List<bool>.generate(im.width, (x) => _colHasContent(im, x, y0, y1));
    final cols = _runs(colContent, colGap);
    for (final c in cols) {
      final x0 = c[0];
      final x1 = c[1];
      if (x1 - x0 < minSpriteSize) continue;
      // 3. Tight-trim this sprite box within [x0,x1) x [y0,y1).
      final trimmed = _tightTrim(im, x0, y0, x1, y1);
      if (trimmed != null &&
          trimmed.w >= minSpriteSize &&
          trimmed.h >= minSpriteSize) {
        rects.add(trimmed);
      }
    }
  }
  return rects;
}

Rect? _tightTrim(img.Image im, int x0, int y0, int x1, int y1) {
  var minX = x1, minY = y1, maxX = x0, maxY = y0;
  var found = false;
  for (var y = y0; y < y1; y++) {
    for (var x = x0; x < x1; x++) {
      if (im.getPixel(x, y).a >= alphaThreshold) {
        found = true;
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
  }
  if (!found) return null;
  const pad = 1;
  minX = (minX - pad).clamp(0, im.width - 1);
  minY = (minY - pad).clamp(0, im.height - 1);
  maxX = (maxX + pad).clamp(0, im.width - 1);
  maxY = (maxY + pad).clamp(0, im.height - 1);
  return Rect(minX, minY, maxX - minX + 1, maxY - minY + 1);
}
